[workspace]
members = [
    "crates/app_core",
    "crates/sim_core",
    "crates/renderer_wgpu",
    "crates/native_app",
    "crates/web_app",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
authors = ["koerner"]

[workspace.dependencies]
bytemuck = { version = "1.15", features = ["derive"] }
glam = "0.27"
pollster = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu = "0.19"
winit = "0.29"
