[package]
name = "native_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pollster.workspace = true
renderer_wgpu = { path = "../renderer_wgpu" }
serde.workspace = true
serde_json.workspace = true
sim_core = { path = "../sim_core" }
wgpu.workspace = true
winit.workspace = true
